### PR TITLE
Adding template to enable backups

### PR DESCRIPTION
**Pull request by andrewpowell**
This template enables the backup of RDS and EFS resources.  An accompanying master template will be committed as well.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by nanux** [comment]
@andrewpowell, thanks for the contribution. What is the intended use for this template? Will that be an optional nested template in the master template?

The template looks quite Jira specific (at least from the naming point of view) but this repository contains only networking layer and database templates and is later used in all 3 products (Jira, Confluence and Bitbucket). Was that intentional?

**Comment by andrewpowell** [comment]
Updated it to be product agnostic.  Tagging a resource supported by AWS Backup (Amazon EBS volumes, Amazon RDS databases, Amazon DynamoDB tables, Amazon EFS file systems, and AWS Storage Gateway volumes) with the tag "backup" and the value "daily" will enable a daily backup of the resource.

**Comment by avattathil** [comment]
@nanux this PR is getting a little long in the tooth!

**Comment by nanux** [comment]
@avattathil we've tested the AWS Backup and it was not a solution we can officially support currently. I would say that we can decline this PR and revisit it potentially in future.

**Pull request closed without merging**
