### PR TITLE
DCD-1316: ssh key description update

### PR DESCRIPTION
**Pull request by jjeongatl**
Description of the 'key Pairs Name SSH' field modified to reduce the confusion during Quickstart set up.

### CODE REVIEW

**Review by ahmadmushtaq5 — APPROVED** [review]

**Comment by tonynv** [comment]
> @tonynv `cfn-lint -a ~/qs-cfn-lint-rules/qs_cfn_lint_rules/` shows no error on local machine. Can you please share how it is running cfn-lint?

The Exception need to in the Metadata section on the template example https://github.com/aws-quickstart/quickstart-atlassian-bitbucket/commit/bf7ee3f8fe5be8ed44835396afcc92e09786cbbd

**Comment by jjeongatl** [comment]
Updated. @tonynv Can we change target path to `templates/*.yaml` so that cfn-lint can ignore config directory and `.filename_standard_exception.txt`

**Comment by tonynv** [comment]
> Updated. @tonynv Can we change target path to `templates/*.yaml` so that cfn-lint can ignore config directory and `.filename_standard_exception.txt`

@jjeongatl 
Yes we can change the target path to only scan `templates/*.yaml` but the cloudwatch config would still be a problem we cannot add excludes to that file because it schema validated.  So the best way to handle it is to move the `config `dir outside of templates dir. The templates dir should only have templates.

**Comment by jjeongatl** [comment]
@tonynv updated

**Pull request merged**
